Parameters:
  VpcName:
    Description: A name that is prefixed to resource names
    Type: String
    Default: "Toanpv4_Ins_CFT"

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.1.0.0/16
    
  PublicSubnetOneCIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.1.1.0/24

  PublicSubnetTwoCIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.1.2.0/24

  # KeyName:
  #   Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  #   Type: AWS::EC2::KeyPair::KeyName
  #   Default: Toanpv4_keypair
  #   ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    # ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VpcName

  PublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnetOneCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub Public Subnet One CFT ${VpcName}

  PublicSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnetTwoCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub Public Subnet Two CFT ${VpcName}

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub InternetGW ${VpcName}

  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub Public RouteTable CFT ${VpcName}                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

  PublicSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetOne
      RouteTableId: !Ref PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachement
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  KeyName:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: Toanpv4_Keypair
      PublicKeyMaterial: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2WnYMt5fz7uYK7UVUEMCrIOd16M75ilij8GHOsDcu4GX5iQjZgjY60hT0BFSE8nMugFdgwgHXfqE0LdtoDBfBf4zjQHaBzsp0GN8FfkmoG5DapboOso+v8pS0yQX6oJLf3SsIVXF1GIO0+UYBgZ1DgrVxpq0TUlxzmtpnOGH+BvTelaK7lZXsgA6V0BujNEeh5FYykeewQRMEsc88rcuVmUX/RFm8UH+JEpRo2asPQ2UEStBiuSxlxAWnp8x3Me/Iw4XGcyUAhhef3IDWri2vaAfoUrA2CM7/Bx+zcW8fz1AzhsB8Cb0fB0TdJX+vmfQ2tdxW5LYbALegz5TXB6X6kNCZ9zD+pFrv9ZE0SUthxmZwW3xrnzqDb7xbKD6kuHLrkY6MNRytQysXr4jBii5F0bHEqlp5YsPTmpB+mOJipIZaJn0E+rglNNws7ovTTVag4kEAsXEECAMt4L4vhmXdy3l1KUIVEu/IbnbAdmp5zU3MIUHcGe25B/IVYNFW0MM= phamtoan@phamtoan

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-02f3416038bdb17fb
      NetworkInterfaces:
        - DeleteOnTermination: true
          Description: Primary network interface
          DeviceIndex: '0'
          SubnetId: !Ref PublicSubnetOne
          GroupSet: [!Ref InstanceSecurityGroup]
          AssociatePublicIpAddress: true
      Tags:
        - Key: Name
          Value: !Sub Instance ${VpcName}
          
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: !Ref SSHLocation
      Tags:
        - Key: Name
          Value: Toanpv4_SG


Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]          